// MERKT [&] associés — Bilingual content (FR / EN)

const I18N = {
  fr: {
    nav: {
      home: "Accueil",
      etude: "L'Étude",
      expertises: "Expertises",
      equipe: "L'Équipe",
      contact: "Contact",
    },
    cta: { contact: "Prendre rendez-vous", explore: "Découvrir l'Étude", all: "Voir toutes les expertises", team: "Rencontrer l'équipe" },
    nowOpen: "Étude ouverte · 8h30 — 18h30",
    motto: "Compétence · Pertinence · Efficacité",
    address: "15, rue du Général-Dufour · 1204 Genève",
    phone: "+41 22 809 55 99",
    fax: "+41 22 809 55 90",
    email: "mail@merkt.ch",

    home: {
      kicker: "Fondée en 1946",
      title_1: "Le droit,",
      title_2: "au cœur de Genève.",
      sub:
        "Une étude de taille humaine, ancrée Place Neuve depuis trois quarts de siècle. Compétence, pertinence, efficacité.",
      facade_caption: "[ photo · façade 15 rue Général-Dufour ]",
      address_label: "Étude · Place Neuve",

      facts_title: "L'Étude en chiffres",
      facts: [
        { k: "1946", v: "Année de fondation" },
        { k: "80", v: "Années d'exercice" },
        { k: "15", v: "Avocats & conseils" },
        { k: "22", v: "Domaines de droit" },
      ],

      manifesto_eyebrow: "Manifeste",
      manifesto_title: "Une institution\nqui regarde devant.",
      manifesto_body:
        "Quatre générations d'avocats, une adresse inchangée face à la Place Neuve, et la conviction que l'exigence se transmet. Nous accompagnons clients privés, dirigeants et groupes internationaux dans la conduite et la résolution de leurs dossiers les plus sensibles, devant toutes les juridictions suisses et dans l'arbitrage international.",

      pillars_eyebrow: "Six piliers · vingt-deux domaines",
      pillars_title: "Nos expertises.",
    },

    etude: {
      eyebrow: "L'Étude",
      title: "Quatre générations,\nune même adresse.",
      lede: "Fondée en 1946 par Me Maurice MERKT, MERKT [&] associés compte parmi les plus anciennes études d'avocats de Genève.",
      timeline: [
        { y: "1946", t: "Fondation par Me Maurice MERKT." },
        { y: "1959", t: "Me René MERKT rejoint son père au barreau ; installation au 15 rue du Général-Dufour, face à la Place Neuve." },
        { y: "1976", t: "Décès de Me Maurice MERKT. Me René MERKT prend la tête de l'Étude, rejoint par Me Jacques MERKT et Me Cyril ABECASSIS." },
        { y: "2003", t: "Me Philippe PASQUIER rejoint le collège des associés." },
        { y: "2013", t: "Nouvelle génération : Me Ronald ASMAR, Me Romain JORDAN et Me Annette MICUCCI deviennent associés." },
        { y: "2022", t: "Me Stéphane GRODECKI rejoint le collège après une longue carrière dans la magistrature genevoise." },
        { y: "2026", t: "L'Étude célèbre ses 80 ans." },
      ],
      values_title: "Nos valeurs",
      values: [
        { k: "Indépendance", v: "Une parole libre, dans le respect strict de la déontologie." },
        { k: "Continuité", v: "Une même adresse, une même exigence, transmises de génération en génération." },
        { k: "Proximité", v: "Une taille humaine qui garantit disponibilité et rapidité d'intervention." },
        { k: "Réseau", v: "Un large réseau de correspondants, en Suisse comme à l'étranger, pour les situations internationales complexes." },
      ],
      affiliations: "Tous les avocats de l'Étude sont membres de l'Ordre des Avocats de Genève (ODA) et de la Fédération Suisse des Avocats (FSA).",
    },

    expertises: {
      eyebrow: "Expertises",
      title: "Vingt-deux domaines,\nsix piliers.",
      lede: "L'Étude intervient en conseil et en contentieux, devant toutes les juridictions cantonales et fédérales, ainsi que dans l'arbitrage international.",
      pillars: [
        {
          n: "01",
          t: "Contentieux & Arbitrage",
          d: "Procédures civile, pénale et administrative ; arbitrage international ; entraides pénale et administrative ; reconnaissance et exequatur de jugements étrangers.",
          items: ["Contentieux interne", "Contentieux international", "Arbitrage", "Entraide pénale et administrative", "Exequatur"],
        },
        {
          n: "02",
          t: "Droit pénal",
          d: "Instruction et conduite des procédures devant le Ministère public et les tribunaux pénaux. Procédures devant les organismes fédéraux (Comco, Swissmedic).",
          items: ["Pénal général", "Pénal économique", "Pénal spécial", "Procédures fédérales"],
        },
        {
          n: "03",
          t: "Droit des affaires & Sociétés",
          d: "Constitution, conseil et restructuration de sociétés. Contrats commerciaux, droit bancaire et financier, fiscalité, propriété intellectuelle.",
          items: ["Droit commercial", "Droit des sociétés", "Bancaire & financier", "Fiscal", "Concurrence", "Propriété intellectuelle"],
        },
        {
          n: "04",
          t: "Patrimoine & Famille",
          d: "Trusts, fondations, planification successorale, divorce et droits parentaux, immobilier et baux, poursuites et faillite.",
          items: ["Successions", "Trusts & fondations", "Famille & divorce", "Immobilier & bail", "Poursuites & faillite"],
        },
        {
          n: "05",
          t: "Droit public & Administratif",
          d: "Constructions, aménagement du territoire et marchés publics. Fonction publique, droit des étrangers, droit disciplinaire.",
          items: ["Constructions & aménagement", "Marchés publics", "Fonction publique", "Étrangers & immigration", "Constitutionnel"],
        },
        {
          n: "06",
          t: "Domaines spécialisés",
          d: "Droit de l'art, de l'aviation, des nouvelles technologies, du travail, de la presse et du droit de l'avocat.",
          items: ["Droit de l'art", "Aviation & navigation aérienne", "Nouvelles technologies", "Travail", "Presse & communication", "Droit de l'avocat"],
        },
      ],
    },

    equipe: {
      eyebrow: "L'Équipe",
      title: "Quinze avocats.\nUne même exigence.",
      lede: "La spécialisation et la complémentarité des compétences de nos associés, qui travaillent toujours en étroite collaboration, garantissent à nos clients un service personnalisé.",
      groups: [
        {
          k: "Associés",
          members: [
            { n: "Philippe PASQUIER", r: "Avocat associé", e: "PhPasquier@merkt.ch", slug: "pasquier" },
            { n: "Ronald ASMAR", r: "Avocat associé", e: "RAsmar@merkt.ch", slug: "asmar" },
            { n: "Romain JORDAN", r: "Avocat associé", e: "RJordan@merkt.ch", slug: "jordan" },
            { n: "Annette MICUCCI", r: "Avocate associée", e: "AMicucci@merkt.ch", slug: "micucci" },
            { n: "Stéphane GRODECKI", r: "Avocat associé", e: "SGrodecki@merkt.ch", slug: "grodecki" },
          ],
        },
        {
          k: "Conseils",
          members: [
            { n: "Laure BOVY", r: "Conseil — ancienne juge cantonale", e: "LBovy@merkt.ch", slug: "bovy" },
            { n: "Cyril ABECASSIS", r: "Avocat conseil", e: "Abecassis@merkt.ch", slug: "abecassis" },
          ],
        },
        {
          k: "Collaborateurs",
          members: [
            { n: "Donika LATIFI", r: "Avocate", e: "DLatifi@merkt.ch", slug: "latifi" },
            { n: "Alexis CONSTAN-TACOPOULOS", r: "Avocat", e: "AConstantacopoulos@merkt.ch", slug: "constantacopoulos" },
            { n: "Nuria HURTADO", r: "Avocate", e: "NHurtado@merkt.ch", slug: "hurtado" },
            { n: "Ludovic PIOLETTI", r: "Avocat", e: "LPioletti@merkt.ch" },
          ],
        },
        {
          k: "Avocats-stagiaires",
          members: [
            { n: "Brian FAVRE", r: "Avocat-stagiaire", e: "BFavre@merkt.ch" },
            { n: "Zachary PICO", r: "Avocat-stagiaire", e: "ZPico@merkt.ch" },
            { n: "Estelle GONET", r: "Avocate-stagiaire", e: "EGonet@merkt.ch" },
          ],
        },
      ],
    },

    contact: {
      eyebrow: "Contact",
      title: "Place Neuve.\nDepuis 1946.",
      lede: "Notre Étude vous accueille du lundi au vendredi, sur rendez-vous.",
      hours_label: "Horaires",
      hours: [
        { d: "Lundi — Jeudi", h: "8h30 — 18h30" },
        { d: "Vendredi", h: "8h30 — 17h30" },
        { d: "Samedi — Dimanche", h: "Sur rendez-vous" },
      ],
      form_title: "Écrivez-nous",
      form: {
        name: "Nom complet",
        email: "Adresse e-mail",
        subject: "Objet",
        message: "Votre message",
        confidential: "Toute correspondance est traitée avec la confidentialité due au secret professionnel de l'avocat.",
        submit: "Envoyer le message",
      },
      sent: "Message reçu. Nous revenons vers vous sous 24 heures.",
    },

    footer: {
      claim: "MERKT [&] associés — Avocats à Genève depuis 1946.",
      legal: "© 2026 MERKT & associés · ODA · FSA",
    },

    avocats: {
      pasquier: {
        name: "Philippe PASQUIER",
        role: "Avocat associé",
        credentials: ["lic. iur.", "lic. ès sc. comm."],
        location: "Genève",
        email: "PhPasquier@merkt.ch",
        photo: "uploads/pasquier.jpg",
        bio: [
          "Philippe PASQUIER est titulaire d'une licence ès sciences commerciales et industrielles (1983) et d'une licence en droit (Master of laws, 1985) de l'Université de Genève. Après avoir effectué son stage d'avocat auprès de MERKT [&] associés, il a obtenu son brevet d'avocat en 1988. Il intègre alors le Comité international de la Croix-Rouge en tant que délégué, affecté au Moyen-Orient et auprès des Nations-Unies à Genève.",
          "Il rejoint ensuite MERKT [&] associés en 1990, et en devient associé en 2003.",
          "Il exerce principalement une activité de conseils (notamment en droit des sociétés et des trusts, en droit fiscal et en planification patrimoniale) et judiciaire (notamment en droit commercial et en droit des successions).",
          "Il est membre de l'Ordre des avocats de Genève et de la Fédération suisse des avocats.",
        ],
        languages_label: "Langues",
        languages: ["Français", "anglais", "espagnol"],
      },
      asmar: {
        name: "Ronald ASMAR",
        role: "Avocat associé",
        credentials: [],
        location: "Genève",
        email: "RAsmar@merkt.ch",
        photo: "uploads/asmar.jpg",
        bio: [
          "Ronald ASMAR est titulaire d'une licence en droit (Master of laws) de l'Université de Genève (2005). Après avoir effectué son stage d'avocat auprès de MERKT [&] associés, il a obtenu son brevet d'avocat en 2007, et a poursuivi son activité comme avocat au sein de l'étude.",
          "Il est associé de MERKT [&] associés depuis janvier 2013.",
          "Il exerce principalement dans les domaines du conseil et de la planification patrimoniale ainsi que du contentieux judiciaire (procédures civile et pénale, notamment droit des contrats, droit des successions, droit de l'art). Il a occupé la fonction de juge suppléant au Tribunal civil de 2013 à 2018.",
          "Il est depuis 2018 membre du conseil de fondation du Musée d'art moderne et contemporain de Genève (MAMCO) dont il est vice-président. Il siège également aux conseils de fondation du Grand Théâtre de Genève et du Conservatoire de Musique de Genève.",
          "Il est membre de l'Ordre des avocats de Genève et de la Fédération Suisse des Avocats.",
        ],
        languages_label: "Langues",
        languages: ["Français", "anglais", "libanais"],
      },
      jordan: {
        name: "Romain JORDAN",
        role: "Avocat associé",
        credentials: ["Juge suppléant à la Cour de justice"],
        location: "Genève",
        email: "RJordan@merkt.ch",
        photo: "uploads/jordan.jpg",
        bio: [
          "Romain JORDAN est titulaire d'une licence en droit (Master of laws) de l'Université de Genève (2005) et d'un certificat de droit transnational (2005). Ayant obtenu son brevet d'avocat en 2007 puis poursuivi son activité au sein d'une étude importante de la place, Romain a rejoint MERKT [&] associés en janvier 2013 en qualité d'associé.",
          "Il occupe la fonction de Juge suppléant à la Cour de justice (dernière instance cantonale) depuis 2021. Modérateur du forum genevois de droit administratif, il intervient régulièrement dans des conférences sur l'actualité juridique.",
          "En plus de ses compétences juridiques, Romain dispose de solides connaissances informatiques — y compris en programmation et bases de données — permettant d'accompagner ses clients lors de toute problématique liant droit et informatique, notamment en cas d'attaques (hacking, ransomware, etc.).",
          "Engagé dans une défense progressive de la cause animale au sein de différentes associations, Me Jordan préside la Fondation pour le développement des arts et de la culture et le Conseil de fondation de l'Orchestre de chambre de Genève. Il est membre de l'ONG humanitaire 123 Action, et préside l'Association suisse des assurés (ASSUAS).",
        ],
        domains_label: "Domaines d'activité",
        domains: "Droit constitutionnel et administratif, conseil de collectivités et entreprises, droit pénal, entraide pénale, droit des contrats, droit des nouvelles technologies, droit de l'aviation, procédure, médiation.",
        languages_label: "Langues",
        languages: ["Français", "anglais", "allemand", "espagnol (bases)"],
      },
      micucci: {
        name: "Annette MICUCCI",
        role: "Avocate associée",
        credentials: ["Spécialiste FSA droit de la famille"],
        location: "Genève",
        email: "AMicucci@merkt.ch",
        photo: "uploads/micucci.jpg",
        bio: [
          "Annette MICUCCI est titulaire d'un bachelor et d'un master en droit de l'Université de Fribourg (2007). Durant l'accomplissement de son master, elle a étudié une année à la Humboldt Universität de Berlin. Après avoir effectué son stage d'avocat auprès d'une étude importante de la place, elle a obtenu son brevet d'avocat en 2010, et a poursuivi son activité comme collaboratrice.",
          "Elle a rejoint MERKT [&] associés en janvier 2013 en tant qu'associée.",
          "Elle exerce principalement une activité dans les divers domaines du contentieux judiciaire, plus particulièrement en droit de la famille, droit des contrats, procédure civile, et droit pénal. Elle est spécialiste FSA droit de la famille.",
          "Membre de l'Ordre des avocats de Genève, elle a siégé au Conseil du Jeune Barreau entre 2013 et 2020, occupé la fonction de Première secrétaire (présidente) du Jeune Barreau de 2016 à 2018, et est membre de la Commission de formation permanente depuis 2014, qu'elle préside depuis le 1er septembre 2025. Elle siège au Conseil de l'Ordre depuis avril 2025.",
          "Me Micucci est membre du Conseil de direction de l'École d'avocature (ECAV) depuis 2021. Elle est membre de la Fédération suisse des avocats et a occupé la fonction de juge assesseur au Tribunal administratif de première instance (2011-2014).",
        ],
        languages_label: "Langues",
        languages: ["Français", "italien", "danois", "anglais", "allemand"],
      },
      grodecki: {
        name: "Stéphane GRODECKI",
        role: "Avocat associé",
        credentials: ["Docteur en droit", "Professeur titulaire à l'Université"],
        location: "Genève",
        email: "SGrodecki@merkt.ch",
        photo: "uploads/grodecki.jpg",
        bio: [
          "Stéphane GRODECKI est titulaire d'une licence en droit (master of laws) de l'Université de Genève (2001 ; prix Huet du Pavillon), du brevet d'avocat (2003), d'un diplôme d'études approfondies en droit public (2005), et d'un doctorat en droit (2007), soutenant une thèse de doctorat en droit constitutionnel couronnée du prix Joseph des Arts en 2008. Il a par ailleurs obtenu un CAS en aide et conseils aux victimes d'infraction (2023), un CAS en protection des données (2024) et un CAS en violence interpersonnelle : aspects et soins médico-légaux (2025).",
          "Il est professeur titulaire de droit public et de droit de la profession d'avocat à l'Université de Genève et a publié plus de 120 contributions scientifiques en droit public, droit pénal et procédure pénale. Il organise et intervient lors de nombreux colloques scientifiques.",
          "Ancien magistrat de l'ordre judiciaire genevois de 2010 à 2021, il a successivement occupé les fonctions de juge suppléant, juge d'instruction, procureur, premier procureur en charge d'une section générale du Ministère public (2012–2016), avant d'être nommé premier procureur en charge des affaires sensibles (2017–2021).",
        ],
        domains_label: "Domaines d'activité",
        domains: "Droit constitutionnel et administratif, conseil aux particuliers, collectivités et entreprises, droit pénal, entraide pénale, droit des contrats, procédure.",
        languages_label: "Langues",
        languages: ["Français", "suisse-allemand", "allemand", "anglais"],
      },
      bovy: {
        name: "Laure BOVY",
        role: "Conseil",
        credentials: ["Conseillère administrative", "a. présidente de la Chambre administrative de la Cour de justice", "a. vice-présidente de la Cour de justice"],
        location: "Genève",
        email: "LBovy@merkt.ch",
        photo: "uploads/bovy.jpg",
        bio: [
          "Laure BOVY est titulaire d'une licence en droit (Master of law) de l'Université de Genève (1970). Après un séjour d'une année à Munich où elle a notamment travaillé en qualité de traductrice pour le Max Planck Institut, elle a effectué son stage d'avocat en l'Étude de Me Jean-Mario TORELLO et a obtenu son brevet d'avocat en 1973.",
          "Elle a rejoint la magistrature en 1993. Elle a occupé à deux reprises la fonction de Présidente de la Chambre administrative de la Cour de justice, puis celle de Vice-présidente de la Cour de justice.",
          "Au sein de la magistrature, elle a siégé pendant six ans au Conseil supérieur de la magistrature, a été membre de la Commission de gestion du Pouvoir Judiciaire et Présidente de la Conférence des Présidents.",
          "Elle a rejoint MERKT [&] associés en qualité de conseil en janvier 2013, où elle déploie une activité de conseil en droit administratif et diligente notamment des enquêtes administratives.",
          "En mars 2020, elle est élue dès le premier tour adjointe au Maire (conseillère administrative) de la commune de Dardagny.",
        ],
        languages_label: "Langues",
        languages: ["Français", "allemand"],
      },
      abecassis: {
        name: "Cyril ABECASSIS",
        role: "Avocat conseil",
        credentials: ["lic. iur.", "lic. ès sc. comm."],
        location: "Genève",
        email: "Abecassis@merkt.ch",
        photo: "uploads/abecassis.jpg",
        bio: [
          "Cyril ABECASSIS est titulaire d'une licence en Droit (Master of laws, 1975) et d'une licence ès Sciences Commerciales et Industrielles (1972) de l'Université de Genève. Après une expérience professionnelle de deux ans dans le négoce international de matières premières, il a effectué son stage d'avocat auprès de l'Étude de Me Pierre SCICLOUNOFF et obtenu son brevet d'avocat en 1980. Il a ensuite exercé comme avocat au sein du cabinet international WHITE & CASE, à New-York et Paris.",
          "Il a rejoint MERKT [&] associés en 1983, position qu'il a quittée avec effet au 1er janvier 2022, devenant Conseil dans ses domaines d'expertise (notamment en droit des sociétés et des trusts, en droit fiscal et en planification patrimoniale).",
        ],
        languages_label: "Langues",
        languages: ["Français", "anglais", "espagnol", "italien"],
      },
      latifi: {
        name: "Donika LATIFI",
        role: "Avocate",
        credentials: [],
        location: "Genève",
        email: "DLatifi@merkt.ch",
        photo: "uploads/latifi.jpg",
        bio: [
          "Donika LATIFI est titulaire d'un bachelor en droit (2015), d'un master en droit de l'Université de Genève (2017) et d'un certificat de spécialisation en matière d'avocature (2018). Durant l'accomplissement de ses études, elle a étudié un an à l'Université de Zurich et un semestre à l'Université de Sydney.",
          "Elle a travaillé au sein de la protection juridique d'une importante compagnie d'assurance (2017–2018), ainsi qu'auprès d'une Étude de la place (2012–2017).",
          "Après l'obtention de son brevet, elle a effectué un mandat de six mois dans des cabinets d'avocats spécialisés dans la défense des victimes de violences conjugales et sexuelles (2021), puis a poursuivi son activité au sein d'une Étude exerçant en droit matrimonial et droit pénal (2021–2022), avant de rejoindre MERKT [&] associés en janvier 2023.",
          "Elle exerce une activité judiciaire dans divers domaines du contentieux, plus particulièrement en droit pénal, droit public et droit du travail. Elle est membre de l'Ordre des avocats de Genève.",
        ],
        languages_label: "Langues",
        languages: ["Français", "albanais", "anglais", "allemand", "espagnol (notions)"],
      },
      constantacopoulos: {
        name: "Alexis CONSTANTACOPOULOS",
        role: "Avocat",
        credentials: [],
        location: "Genève",
        email: "AConstantacopoulos@merkt.ch",
        photo: null,
        bio: [
          "Alexis CONSTANTACOPOULOS est titulaire d'un baccalauréat et d'une maîtrise en droit de l'Université de Genève, du certificat de spécialisation en matière d'avocature (2016) et du brevet d'avocat (2017), ainsi que d'un baccalauréat de l'École des Hautes Études Commerciales (HEC) de l'Université de Lausanne (2006), du diplôme de Chartered Alternative Investment Analyst (2011) et d'un CAS en management de l'énergie de l'Université de Genève (2012).",
          "Il a débuté sa carrière dans les secteurs de l'investissement alternatif (hedge funds) et de l'immobilier, avant de pratiquer le droit au sein d'une Étude genevoise durant plus de six ans, en particulier dans les domaines du droit des médias, des nouvelles technologies (protection des données) et de l'exécution forcée (poursuites et faillites).",
          "Il a rejoint MERKT [&] associés au début de l'année 2023, en qualité de collaborateur. Il est membre de l'Ordre des avocats de Genève.",
        ],
        languages_label: "Langues",
        languages: ["Français", "grec", "anglais", "allemand"],
      },
      hurtado: {
        name: "Nuria HURTADO",
        role: "Avocate",
        credentials: [],
        location: "Genève",
        email: "NHurtado@merkt.ch",
        photo: "uploads/hurtado.jpg",
        bio: [],
        languages_label: "Langues",
        languages: [],
      },
    },
  },

  en: {
    nav: {
      home: "Home",
      etude: "The Firm",
      expertises: "Expertise",
      equipe: "Team",
      contact: "Contact",
    },
    cta: { contact: "Schedule a meeting", explore: "About the Firm", all: "All practice areas", team: "Meet the team" },
    nowOpen: "Open · 8:30 — 18:30",
    motto: "Competence · Relevance · Efficiency",
    address: "15, rue du Général-Dufour · 1204 Geneva",
    phone: "+41 22 809 55 99",
    fax: "+41 22 809 55 90",
    email: "mail@merkt.ch",

    home: {
      kicker: "Established 1946",
      title_1: "Counsel,",
      title_2: "at the heart of Geneva.",
      sub:
        "A boutique firm rooted on Place Neuve for three quarters of a century. Competence, relevance, efficiency.",
      facade_caption: "[ photograph · 15 rue Général-Dufour façade ]",
      address_label: "Office · Place Neuve",

      facts_title: "The firm in numbers",
      facts: [
        { k: "1946", v: "Year founded" },
        { k: "80", v: "Years in practice" },
        { k: "15", v: "Lawyers & counsels" },
        { k: "22", v: "Areas of law" },
      ],

      manifesto_eyebrow: "Manifesto",
      manifesto_title: "An institution\nthat looks ahead.",
      manifesto_body:
        "Four generations of lawyers, an unchanged address opposite Place Neuve, and the conviction that excellence is passed down. We advise individuals, executives and international groups on their most demanding matters, before every Swiss jurisdiction and in international arbitration.",

      pillars_eyebrow: "Six pillars · twenty-two practice areas",
      pillars_title: "Our expertise.",
    },

    etude: {
      eyebrow: "The Firm",
      title: "Four generations,\none address.",
      lede: "Founded in 1946 by Me Maurice MERKT, MERKT [&] associés is among the oldest law firms in Geneva.",
      timeline: [
        { y: "1946", t: "Founded by Me Maurice MERKT." },
        { y: "1959", t: "Me René MERKT joins his father; the firm settles at 15 rue du Général-Dufour, opposite Place Neuve." },
        { y: "1976", t: "After Me Maurice MERKT's passing, Me René MERKT leads the firm and is joined by Me Jacques MERKT and Me Cyril ABECASSIS." },
        { y: "2003", t: "Me Philippe PASQUIER joins as a partner." },
        { y: "2013", t: "A new generation: Me Ronald ASMAR, Me Romain JORDAN and Me Annette MICUCCI become partners." },
        { y: "2022", t: "Me Stéphane GRODECKI joins after a distinguished career in the Geneva judiciary." },
        { y: "2026", t: "The firm celebrates its 80th anniversary." },
      ],
      values_title: "Our values",
      values: [
        { k: "Independence", v: "A free voice, within strict ethical bounds." },
        { k: "Continuity", v: "One address, one standard, passed down across generations." },
        { k: "Proximity", v: "A boutique scale that guarantees availability and speed of intervention." },
        { k: "Network", v: "A broad network of correspondents in Switzerland and abroad for complex international situations." },
      ],
      affiliations: "All lawyers of the firm are members of the Geneva Bar Association (ODA) and the Swiss Bar Association (FSA).",
    },

    expertises: {
      eyebrow: "Expertise",
      title: "Twenty-two areas,\nsix pillars.",
      lede: "The firm advises and litigates before every Swiss cantonal and federal jurisdiction, and in international arbitration.",
      pillars: [
        { n: "01", t: "Litigation & Arbitration", d: "Civil, criminal and administrative proceedings; international arbitration; mutual legal assistance; recognition and enforcement of foreign judgments.", items: ["Domestic litigation", "International litigation", "Arbitration", "Mutual assistance", "Enforcement"] },
        { n: "02", t: "Criminal Law", d: "Investigation and conduct of proceedings before the Public Prosecutor and criminal courts. Proceedings before federal bodies (Comco, Swissmedic).", items: ["General criminal", "White-collar", "Special criminal", "Federal proceedings"] },
        { n: "03", t: "Corporate & Business", d: "Incorporation, advice and restructuring. Commercial contracts, banking and finance, tax, intellectual property.", items: ["Commercial", "Corporate", "Banking & finance", "Tax", "Competition", "Intellectual property"] },
        { n: "04", t: "Wealth & Family", d: "Trusts, foundations, estate planning, divorce and parental rights, real estate and leases, debt collection and bankruptcy.", items: ["Estates", "Trusts & foundations", "Family & divorce", "Real estate & leases", "Debt collection"] },
        { n: "05", t: "Public & Administrative", d: "Construction, town planning and public procurement. Civil service, immigration, disciplinary law.", items: ["Construction & planning", "Public procurement", "Civil service", "Immigration", "Constitutional"] },
        { n: "06", t: "Specialised Practices", d: "Art law, aviation, new technologies, employment, press and the law of the legal profession.", items: ["Art law", "Aviation", "New technologies", "Employment", "Press & media", "Law of the profession"] },
      ],
    },

    equipe: {
      eyebrow: "Team",
      title: "Fifteen lawyers.\nOne standard.",
      lede: "The specialisation and complementarity of our partners, who work in close collaboration, guarantee personalised service to our clients.",
      groups: [
        {
          k: "Partners",
          members: [
            { n: "Philippe PASQUIER", r: "Partner", e: "PhPasquier@merkt.ch", slug: "pasquier" },
            { n: "Ronald ASMAR", r: "Partner", e: "RAsmar@merkt.ch", slug: "asmar" },
            { n: "Romain JORDAN", r: "Partner", e: "RJordan@merkt.ch", slug: "jordan" },
            { n: "Annette MICUCCI", r: "Partner", e: "AMicucci@merkt.ch", slug: "micucci" },
            { n: "Stéphane GRODECKI", r: "Partner", e: "SGrodecki@merkt.ch", slug: "grodecki" },
          ],
        },
        {
          k: "Counsels",
          members: [
            { n: "Laure BOVY", r: "Counsel — former cantonal judge", e: "LBovy@merkt.ch", slug: "bovy" },
            { n: "Cyril ABECASSIS", r: "Of counsel", e: "Abecassis@merkt.ch", slug: "abecassis" },
          ],
        },
        {
          k: "Associates",
          members: [
            { n: "Donika LATIFI", r: "Associate", e: "DLatifi@merkt.ch", slug: "latifi" },
            { n: "Alexis CONSTAN-TACOPOULOS", r: "Associate", e: "AConstantacopoulos@merkt.ch", slug: "constantacopoulos" },
            { n: "Nuria HURTADO", r: "Associate", e: "NHurtado@merkt.ch", slug: "hurtado" },
            { n: "Ludovic PIOLETTI", r: "Associate", e: "LPioletti@merkt.ch" },
          ],
        },
        {
          k: "Trainee lawyers",
          members: [
            { n: "Brian FAVRE", r: "Trainee", e: "BFavre@merkt.ch" },
            { n: "Zachary PICO", r: "Trainee", e: "ZPico@merkt.ch" },
            { n: "Estelle GONET", r: "Trainee", e: "EGonet@merkt.ch" },
          ],
        },
      ],
    },

    contact: {
      eyebrow: "Contact",
      title: "Place Neuve.\nSince 1946.",
      lede: "Our office welcomes you from Monday to Friday, by appointment.",
      hours_label: "Office hours",
      hours: [
        { d: "Monday — Thursday", h: "8:30 — 18:30" },
        { d: "Friday", h: "8:30 — 17:30" },
        { d: "Saturday — Sunday", h: "By appointment" },
      ],
      form_title: "Write to us",
      form: {
        name: "Full name",
        email: "Email address",
        subject: "Subject",
        message: "Your message",
        confidential: "All correspondence is treated with the confidentiality of attorney-client privilege.",
        submit: "Send message",
      },
      sent: "Message received. We will reply within 24 hours.",
    },

    footer: {
      claim: "MERKT [&] associés — Lawyers in Geneva since 1946.",
      legal: "© 2026 MERKT & associés · ODA · FSA",
    },

    avocats: {
      pasquier: {
        name: "Philippe PASQUIER",
        role: "Partner",
        credentials: ["lic. iur.", "lic. ès sc. comm."],
        location: "Geneva",
        email: "PhPasquier@merkt.ch",
        photo: "uploads/pasquier.jpg",
        bio: [
          "Philippe PASQUIER holds a degree in commercial and industrial sciences (1983) and a degree in law (Master of Laws, 1985) from the University of Geneva. After completing his traineeship at MERKT [&] associés, he was admitted to the Bar in 1988. He then joined the International Committee of the Red Cross as a delegate, posted to the Middle East and to the United Nations in Geneva.",
          "He subsequently rejoined MERKT [&] associés in 1990 and became a partner in 2003.",
          "He practises primarily in advisory work (notably in company and trust law, tax law, and estate planning) and in litigation (notably in commercial law and the law of succession).",
          "He is a member of the Geneva Bar Association and the Swiss Bar Association.",
        ],
        languages_label: "Languages",
        languages: ["French", "English", "Spanish"],
      },
      asmar: {
        name: "Ronald ASMAR",
        role: "Partner",
        credentials: [],
        location: "Geneva",
        email: "RAsmar@merkt.ch",
        photo: "uploads/asmar.jpg",
        bio: [
          "Ronald ASMAR holds a law degree (Master of Laws) from the University of Geneva (2005). After completing his traineeship at MERKT [&] associés, he was admitted to the Bar in 2007 and continued practising within the firm.",
          "He has been a partner of MERKT [&] associés since January 2013.",
          "He practises primarily in advisory and estate planning matters as well as litigation (civil and criminal proceedings, notably contract law, succession law, and art law). He served as a deputy judge at the Civil Court from 2013 to 2018.",
          "Since 2018 he has been a board member of the Musée d'art moderne et contemporain de Genève (MAMCO), where he serves as vice-president, as well as board member of the Grand Théâtre de Genève and the Geneva Conservatory of Music.",
          "He is a member of the Geneva Bar Association and the Swiss Bar Association.",
        ],
        languages_label: "Languages",
        languages: ["French", "English", "Lebanese Arabic"],
      },
      jordan: {
        name: "Romain JORDAN",
        role: "Partner",
        credentials: ["Deputy judge at the Court of Justice"],
        location: "Geneva",
        email: "RJordan@merkt.ch",
        photo: "uploads/jordan.jpg",
        bio: [
          "Romain JORDAN holds a law degree (Master of Laws) from the University of Geneva (2005) and a certificate in transnational law (2005). Admitted to the Bar in 2007, he joined MERKT [&] associés in January 2013 as a partner.",
          "He has served as deputy judge at the Court of Justice (the highest cantonal court) since 2021, and regularly speaks at conferences on current legal issues.",
          "In addition to his legal expertise, Romain has substantial knowledge of computer science — including programming and databases — enabling him to assist clients in matters at the intersection of law and technology, including cyber-attacks (hacking, ransomware, etc.).",
          "He chairs the Foundation for the Development of Arts and Culture and the Foundation Council of the Geneva Chamber Orchestra, is a member of the NGO 123 Action, and chairs the Swiss Insured Persons' Association (ASSUAS).",
        ],
        domains_label: "Practice areas",
        domains: "Constitutional and administrative law, advice to public bodies and businesses, criminal law, mutual legal assistance, contract law, technology law, aviation law, procedure, mediation.",
        languages_label: "Languages",
        languages: ["French", "English", "German", "Spanish (basics)"],
      },
      micucci: {
        name: "Annette MICUCCI",
        role: "Partner",
        credentials: ["FSA Family Law Specialist"],
        location: "Geneva",
        email: "AMicucci@merkt.ch",
        photo: "uploads/micucci.jpg",
        bio: [
          "Annette MICUCCI holds a bachelor's and a master's degree in law from the University of Fribourg (2007), including one year of study at Humboldt Universität zu Berlin. Admitted to the Bar in 2010, she joined MERKT [&] associés as a partner in January 2013.",
          "She practises primarily in litigation, with a particular focus on family law, contract law, civil procedure, and criminal law. She holds the FSA specialist qualification in family law.",
          "She has served on the Young Bar Council (2013–2020), as First Secretary (President) of the Young Bar (2016–2018), and on the Continuing Education Committee since 2014, which she has chaired since September 2025. She has been a member of the Bar Council since April 2025 and of the Executive Committee of the Geneva Bar School (ECAV) since 2021.",
        ],
        languages_label: "Languages",
        languages: ["French", "Italian", "Danish", "English", "German"],
      },
      grodecki: {
        name: "Stéphane GRODECKI",
        role: "Partner",
        credentials: ["Doctor of Law", "Full Professor at the University of Geneva"],
        location: "Geneva",
        email: "SGrodecki@merkt.ch",
        photo: "uploads/grodecki.jpg",
        bio: [
          "Stéphane GRODECKI holds a law degree (Master of Laws) from the University of Geneva (2001; Huet du Pavillon Prize), a Bar certificate (2003), a diploma of advanced studies in public law (2005), and a doctorate in constitutional law (2007), awarded the Prix Joseph des Arts in 2008.",
          "He is a full professor of public law and legal professional ethics at the University of Geneva and has published over 120 scholarly contributions. He regularly organises and participates in academic conferences.",
          "A former member of the Geneva judiciary from 2010 to 2021, he successively served as deputy judge, investigating judge, prosecutor, Chief Prosecutor heading a general section (2012–2016), and Chief Prosecutor for sensitive matters (2017–2021).",
        ],
        domains_label: "Practice areas",
        domains: "Constitutional and administrative law, advice to individuals, public bodies and businesses, criminal law, mutual legal assistance, contract law, procedure.",
        languages_label: "Languages",
        languages: ["French", "Swiss German", "German", "English"],
      },
      bovy: {
        name: "Laure BOVY",
        role: "Counsel",
        credentials: ["Municipal Councillor", "Former President, Administrative Chamber, Court of Justice", "Former Vice-President, Court of Justice"],
        location: "Geneva",
        email: "LBovy@merkt.ch",
        photo: "uploads/bovy.jpg",
        bio: [
          "Laure BOVY holds a law degree (Master of Law) from the University of Geneva (1970). After a year in Munich, she completed her traineeship at the office of Me Jean-Mario TORELLO and was admitted to the Bar in 1973.",
          "She joined the judiciary in 1993, serving twice as President of the Administrative Chamber of the Court of Justice and as Vice-President of the Court of Justice. She also sat on the Superior Council of the Judiciary for six years.",
          "She joined MERKT [&] associés as counsel in January 2013, advising primarily in administrative law and conducting administrative investigations.",
          "In March 2020, she was elected Municipal Councillor (Administrative Councillor) of the commune of Dardagny.",
        ],
        languages_label: "Languages",
        languages: ["French", "German"],
      },
      abecassis: {
        name: "Cyril ABECASSIS",
        role: "Of Counsel",
        credentials: ["lic. iur.", "lic. ès sc. comm."],
        location: "Geneva",
        email: "Abecassis@merkt.ch",
        photo: "uploads/abecassis.jpg",
        bio: [
          "Cyril ABECASSIS holds a law degree (Master of Laws, 1975) and a degree in commercial and industrial sciences (1972) from the University of Geneva. After two years in international commodity trading, he completed his traineeship at the office of Me Pierre SCICLOUNOFF and was admitted to the Bar in 1980. He then practised at the international firm WHITE & CASE in New York and Paris.",
          "He joined MERKT [&] associés in 1983 and stepped back from his partnership on 1 January 2022, becoming Of Counsel in his core areas of expertise (company and trust law, tax law, and estate planning).",
        ],
        languages_label: "Languages",
        languages: ["French", "English", "Spanish", "Italian"],
      },
      latifi: {
        name: "Donika LATIFI",
        role: "Associate",
        credentials: [],
        location: "Geneva",
        email: "DLatifi@merkt.ch",
        photo: "uploads/latifi.jpg",
        bio: [
          "Donika LATIFI holds a bachelor's and a master's degree in law from the University of Geneva (2015, 2017) and a certificate of specialisation in legal practice (2018), including study at the University of Zurich and the University of Sydney.",
          "After working in legal protection at a major insurance company and at a Geneva firm, she completed a six-month mandate specialising in the defence of victims of domestic and sexual violence (2021), then practised in matrimonial and criminal law (2021–2022), before joining MERKT [&] associés in January 2023.",
          "She practises in litigation, with a particular focus on criminal law, public law, and employment law. She is a member of the Geneva Bar Association.",
        ],
        languages_label: "Languages",
        languages: ["French", "Albanian", "English", "German", "Spanish (basic)"],
      },
      constantacopoulos: {
        name: "Alexis CONSTANTACOPOULOS",
        role: "Associate",
        credentials: [],
        location: "Geneva",
        email: "AConstantacopoulos@merkt.ch",
        photo: null,
        bio: [
          "Alexis CONSTANTACOPOULOS holds a bachelor's and a master's degree in law from the University of Geneva, a Bar certificate (2017), a bachelor's degree from HEC Lausanne (2006), the Chartered Alternative Investment Analyst diploma (2011), and a CAS in energy management from the University of Geneva (2012).",
          "He began his career in alternative investment (hedge funds) and real estate before practising law at a Geneva firm for over six years, focusing on media law, technology law (data protection), and enforcement proceedings.",
          "He joined MERKT [&] associés at the beginning of 2023 as an associate. He is a member of the Geneva Bar Association.",
        ],
        languages_label: "Languages",
        languages: ["French", "Greek", "English", "German"],
      },
      hurtado: {
        name: "Nuria HURTADO",
        role: "Associate",
        credentials: [],
        location: "Geneva",
        email: "NHurtado@merkt.ch",
        photo: "uploads/hurtado.jpg",
        bio: [],
        languages_label: "Languages",
        languages: [],
      },
    },
  },
};

window.I18N = I18N;
